import { execSync } from 'child_process';

function runAudit() {
  const targetBranch = process.env.PR_TARGET_BRANCH || 'main';
  
  console.log(`Running PR audit against ${targetBranch}...`);
  
  let jsonOutput = '';
  try {
    jsonOutput = execSync(`node ./bin/outlier.js --json --since ${targetBranch}`, {
      stdio: ['ignore', 'pipe', 'ignore'],
      maxBuffer: 1024 * 1024 * 10
    }).toString();
  } catch (err: any) {
    console.error("Failed to run outlier audit", err.message);
    process.exit(1);
  }

  let data;
  try {
    data = JSON.parse(jsonOutput);
  } catch (err) {
    console.error("Failed to parse outlier JSON output:", jsonOutput);
    process.exit(1);
  }

  const authorship = data.authorship;
  if (!authorship) {
    console.log("No authorship data found.");
    process.exit(0);
  }

  const contrib = authorship.contribution;
  if (!contrib) {
    console.log("No contribution profile found.");
    process.exit(0);
  }

  const aiShare = contrib.execution.aiPercent;
  const prompts = contrib.intent.prompts !== null ? contrib.intent.prompts : 'Unknown';
  const rework = (contrib.oversight.iterationRate * 100).toFixed(0) + '%';
  const judgment = contrib.judgment;
  const label = contrib.label;
  const deskillingRisk = aiShare > 70 && Number(prompts) < 10 ? 'HIGH' : aiShare > 40 ? 'MODERATE' : 'LOW';
  
  const nonCodePts = contrib.nonCode?.points || 0;

  const markdownComment = `
## OUTLIER PR AUDIT
**Tokens Burnt vs Human Judgement**

- **Execution AI Share:** \`${aiShare}%\`
- **Deskilling Risk:** \`${deskillingRisk}\`
- **Cognitive Budget:** 
  - Intent: \`${prompts} Prompts\`
  - Oversight: \`${rework} Rework\`
- **Non-Code Contributions:** \`${nonCodePts} Points\`

### Verdict: ${label}
> ${judgment}

*Generated by [outlier](https://github.com/rosh100yx/outlier) — Zero-Trust, Local-First AI Measurement.*
  `.trim();

  console.log("\n--- PR COMMENT PREVIEW ---\n");
  console.log(markdownComment);
  console.log("\n--------------------------\n");

  // If in CI context, we would post this to the PR using GitHub Actions / gh CLI.
}

runAudit();
