import pc from 'picocolors';
import { execSync } from 'child_process';
import { select, isCancel } from '@clack/prompts';

export interface AuditStats {
  aiLines: number;
  humanPct: number;
  tokens: string;
  cachePct: string;
  usd: string;
  yieldPct: number | null;
  radius: string;
}

const MUSK_QUOTES = [
  "I just burnt {tokens} tokens on a typo. Am I funding Sam Altman's yacht?",
  "My AI Context Tax is {cachePct}%. I am literally paying AI to read my bad code over and over.",
  "Token maxxing: {tokens} read, {aiLines} lines actually kept. Peak 10x developer energy.",
  "My local AI agent is doing more work than me. Total daily cost: ${usd}. Worth it.",
  "I only wrote {humanPct}% of my own codebase today. I am no longer a SWE, I am a prompt manager.",
  "AI wrote {aiLines} lines of code for me today. I have absolutely no idea how my app works anymore.",
  "My Code Yield is {yieldPct}%. I am basically just an API key with a pulse.",
  "My deskilling risk is 'Critical'. I am one Claude API outage away from losing my job.",
  "I gave an autonomous agent {radius} blast radius. Pray for my production database.",
  "Is my AI quietly building a backdoor? Asking for a friend. (Blast radius: {radius})",
  "My AI just committed {aiLines} lines. Who needs CI/CD when you have vibes?",
  "Zero-trust architecture... except for the AI agent that has full read/write access to my machine.",
  "If this code breaks in production, it's not my fault. Take it up with the LLM.",
  "I used to be a Senior Engineer. Now I'm just a babysitter for a local LLM.",
  "I need to be safer with AI agents controlling my product build... but I won't."
];

function wrapText(text: string, maxLen: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + word).length > maxLen) {
      lines.push(currentLine.trim());
      currentLine = word + ' ';
    } else {
      currentLine += word + ' ';
    }
  }
  lines.push(currentLine.trim());
  return lines;
}

export async function promptShareAudit(stats: AuditStats) {
  const answer = await select({
    message: 'What would you like to do with this audit?',
    options: [
      { value: 'none', label: '🚪 Exit' },
      { value: 'share', label: '📢 Share flex receipt (Anonymized ASCII)' },
      { value: 'discuss', label: '🤖 Discuss with AI' }
    ]
  });

  if (isCancel(answer) || answer === 'none') {
    return;
  }

  if (answer === 'discuss') {
    const chatUrl = `https://chatgpt.com/?q=${encodeURIComponent("Here is my code audit stats. My AI yield is " + (stats.yieldPct ?? "unknown") + "% and my context cache is " + stats.cachePct + "%. How do I improve my prompt efficiency?")}`;
    console.log(`\n ${pc.cyan('→')} Discuss with ChatGPT: \x1b]8;;${chatUrl}\x07${pc.underline('Click Here')}\x1b]8;;\x07`);
    return;
  }

  if (answer === 'share') {
    const quoteTemplate = (MUSK_QUOTES[Math.floor(Math.random() * MUSK_QUOTES.length)] as string);
    const text = quoteTemplate
      .replace('{tokens}', stats.tokens)
      .replace('{cachePct}', stats.cachePct)
      .replace('{aiLines}', stats.aiLines.toString())
      .replace('{usd}', stats.usd)
      .replace('{humanPct}', stats.humanPct.toFixed(1))
      .replace('{yieldPct}', stats.yieldPct ? stats.yieldPct.toFixed(1) : 'unknown')
      .replace('{radius}', stats.radius);

    const wrapped = wrapText(text, 62);
    let bubbleLines = wrapped.map(l => ` │ "${l.padEnd(62)}" │`).join('\n');

    const asciiArt = `
 ┌──────────────────────────────────────────────────────────────────┐
${bubbleLines}
 └─┬────────────────────────────────────────────────────────────────┘
   │
  [🤖] — Audit generated by outlier
         Code Yield: ${stats.yieldPct ? stats.yieldPct.toFixed(1) + '%' : 'N/A'} | Context Tax: ${stats.cachePct}%
`;

    console.log(pc.bold(pc.magenta('\n Your Quirky Confession Receipt:')));
    console.log(pc.dim(asciiArt));

    // Try to copy to clipboard
    try {
      if (process.platform === 'darwin') {
        execSync('pbcopy', { input: asciiArt.trim() });
        console.log(` ${pc.green('✓')} Copied to clipboard! Ready to paste in Slack/Discord/X.`);
      } else if (process.platform === 'win32') {
        execSync('clip', { input: asciiArt.trim() });
        console.log(` ${pc.green('✓')} Copied to clipboard!`);
      } else {
        // Linux might not have xclip installed, just print
      }
    } catch (e) {
      // ignore
    }

    const twitterText = encodeURIComponent(`Outlier Code Audit:\n\n"${text}"\n\nCode Yield: ${stats.yieldPct ? stats.yieldPct.toFixed(1) + '%' : 'N/A'}\nContext Tax: ${stats.cachePct}%\n\n#10xDeveloper #AI`);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${twitterText}`;
    
    console.log(`\n ${pc.cyan('→')} Share on X/Twitter: \x1b]8;;${twitterUrl}\x07${pc.underline('Click Here')}\x1b]8;;\x07\n`);
  }
}
