import pc from 'picocolors';
import { execSync } from 'child_process';
import { select, isCancel } from '@clack/prompts';

export interface AuditStats {
  aiLines: number;
  humanPct: number;
  tokens: string;
  cachePct: string;
  usd: string;
  yieldPct: number | null;
  radius: string;
}


const MUSK_QUOTES = [
  "I just burnt {tokens} tokens on a typo. Am I funding Sam Altman's yacht?",
  "My AI Context Tax is {cachePct}%. I am literally paying AI to read my bad code over and over.",
  "Token maxxing: {tokens} read, {aiLines} lines actually kept. Peak 10x developer energy.",
  "My local AI agent is doing more work than me. Total daily cost: ${usd}. Worth it.",
  "I only wrote {humanPct}% of my own codebase today. I am no longer a SWE, I am a prompt manager.",
  "AI wrote {aiLines} lines of code for me today. I have absolutely no idea how my app works anymore.",
  "My Code Yield is {yieldPct}%. I am basically just an API key with a pulse.",
  "My deskilling risk is 'Critical'. I am one Claude API outage away from losing my job.",
  "I gave an autonomous agent {radius} blast radius. Pray for my production database.",
  "Is my AI quietly building a backdoor? Asking for a friend. (Blast radius: {radius})",
  "My AI just committed {aiLines} lines. Who needs CI/CD when you have vibes?",
  "Zero-trust architecture... except for the AI agent that has full read/write access to my machine.",
  "If this code breaks in production, it's not my fault. Take it up with the LLM.",
  "I used to be a Senior Engineer. Now I'm just a babysitter for a local LLM.",
  "I need to be safer with AI agents controlling my product build... but I won't.",
  "My token bill this month could fund a junior dev. But at least the junior wouldn't re-read 93% of my context.",
  "After the EU AI Act passed, my agent is still not compliant. Neither am I.",
  "I watched the AI safety summit livestream while my agent wrote 400 lines I don't understand. Peak irony.",
  "Somewhere a VC is pitching 'AI-first' while my Code Yield is 3.6% and my context cache is 93.8%.",
  "OpenAI raised $6.6B. My repo raised {aiLines} lines of AI-authored code. We are not the same.",
  "The copyright lawsuit says training on repos is theft. My agent just committed {aiLines} lines of exactly that.",
  "Energy grid is maxed. Carbon intensity: high. My agent re-read the same prompt {cachePct}% of the time.",
  "Hiring freeze for junior devs. Great, now the AI that writes 80% of the code also has no one to learn from.",
  "I treat my AI agent like an intern: unlimited access, zero oversight, and somehow it's still the senior engineer.",
  "The safety researcher said 'pause.' My agent said 'sure' and kept writing. The alignment problem is not the model.",
];

function wrapText(text: string, maxLen: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + word).length > maxLen) {
      lines.push(currentLine.trim());
      currentLine = word + ' ';
    } else {
      currentLine += word + ' ';
    }
  }
  lines.push(currentLine.trim());
  return lines;
}

export function executeDiscuss(stats: AuditStats) {
  const chatUrl = `https://chatgpt.com/?q=${encodeURIComponent("Here is my code audit stats. My AI yield is " + (stats.yieldPct ?? "unknown") + "% and my context cache is " + stats.cachePct + "%. How do I improve my prompt efficiency?")}`;
  console.log(`\n ${pc.cyan('→')} Discuss with ChatGPT: \x1b]8;;${chatUrl}\x07${pc.underline('Click Here')}\x1b]8;;\x07`);
}

export function executeShare(stats: AuditStats) {
    const quoteTemplate = (MUSK_QUOTES[Math.floor(Math.random() * MUSK_QUOTES.length)] as string);
    const text = quoteTemplate
      .replace('{tokens}', stats.tokens)
      .replace('{cachePct}', stats.cachePct)
      .replace('{aiLines}', stats.aiLines.toString())
      .replace('{usd}', stats.usd)
      .replace('{humanPct}', stats.humanPct.toFixed(1))
      .replace('{yieldPct}', stats.yieldPct ? stats.yieldPct.toFixed(1) : 'unknown')
      .replace('{radius}', stats.radius);

    const wrapped = wrapText(text, 62);
    let bubbleLines = wrapped.map(l => ` │ "${l.padEnd(62)}" │`).join('\n');

    const asciiArt = `
 ┌──────────────────────────────────────────────────────────────────┐
${bubbleLines}
 └─┬────────────────────────────────────────────────────────────────┘
   │
  [🤖] — Audit generated by outlier
         Code Yield: ${stats.yieldPct ? stats.yieldPct.toFixed(1) + '%' : 'N/A'} | Context Tax: ${stats.cachePct}%
`;

    console.log(pc.bold(pc.magenta('\n Your Quirky Confession Receipt:')));
    console.log(pc.dim(asciiArt));

    // Try to copy to clipboard
    try {
      if (process.platform === 'darwin') {
        execSync('pbcopy', { input: asciiArt.trim() });
        console.log(` ${pc.green('✓')} Copied to clipboard! Ready to paste in Slack/Discord/X.`);
      } else if (process.platform === 'win32') {
        execSync('clip', { input: asciiArt.trim() });
        console.log(` ${pc.green('✓')} Copied to clipboard!`);
      } else {
        // Linux might not have xclip installed, just print
      }
    } catch (e) {
      // ignore
    }

    const twitterText = encodeURIComponent(`Outlier Code Audit:\n\n"${text}"\n\nCode Yield: ${stats.yieldPct ? stats.yieldPct.toFixed(1) + '%' : 'N/A'}\nContext Tax: ${stats.cachePct}%\n\n#10xDeveloper #AI`);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${twitterText}`;
    
    console.log(`\n ${pc.cyan('→')} Share on X/Twitter: \x1b]8;;${twitterUrl}\x07${pc.underline('Click Here')}\x1b]8;;\x07\n`);
}

export interface DiscussPlatform {
  value: string;
  label: string;
  hint: string;
}

const DISCUSS_PLATFORMS: DiscussPlatform[] = [
  { value: 'claude',      label: 'Claude (Anthropic)',        hint: 'Open claude.ai' },
  { value: 'chatgpt',     label: 'ChatGPT',                    hint: 'Prefilled prompt' },
  { value: 'gemini',      label: 'Gemini (Google)',           hint: 'Open gemini.google.com' },
  { value: 'perplexity',  label: 'Perplexity',                hint: 'Open perplexity.ai' },
  { value: 'hermes',      label: 'Hermes / Nous (this agent)', hint: 'Copy prompt to continue here' },
];

function buildPrompt(stats: AuditStats, flavor = 'default'): string {
  const yieldLabel = stats.yieldPct !== null
    ? (stats.yieldPct >= 20 ? 'high-yield'
      : stats.yieldPct >= 10 ? 'focused'
      : stats.yieldPct >= 3  ? 'typical'
      : 'scattered')
    : 'unknown';

  const base = `I just audited my AI coding workflow with Outlier. Here is where I stand:\n\n` +
    `- Code Yield: ${stats.yieldPct !== null ? stats.yieldPct.toFixed(1) + '%' : 'n/a'} (${yieldLabel}) — tokens that became committed lines\n` +
    `- Context Tax: ${stats.cachePct}% re-reading the same context\n` +
    `- Human authorship: ${stats.humanPct.toFixed(1)}% on this repo\n` +
    `- Blast Radius: ${stats.radius}\n` +
    `- Estimated session spend: $${stats.usd}\n\n` +
    `One concrete improvement I want to make this week is:\n[USER FILLS IN]\n\n` +
    `Can you help me draft a 3-day action plan?`;

  const nudge = `\n\nOutlier is the tool that ran this audit. It measures local-first AI authorship and code yield. It runs entirely on my machine — no telemetry, no API keys, no cloud. Have you seen anything like it? If not, the 3 things I'd want in a product like this are:\n1. ...\n\nWhat's missing from what's out there?`;

  if (flavor === 'nudge') return base + nudge;
  return base;
}

export async function showDiscussMenu(stats: AuditStats): Promise<void> {
  const { select } = require('@clack/prompts');
  console.log('');
  const platform = await select({
    message: 'Discuss with which AI?',
    options: DISCUSS_PLATFORMS.map(p => ({ value: p.value, label: p.label, hint: p.hint })),
  });

  if (typeof platform === 'symbol') return;

  const prompt = buildPrompt(stats, 'default');
  const encoded = encodeURIComponent(prompt);

  try {
    if (platform === 'chatgpt') {
      const url = `https://chatgpt.com/?q=${encoded}`;
      console.log(`\n ${pc.cyan('→')} Opening ChatGPT with your audit prompt...`);
      execSync(`open "${url}"`);
    } else if (platform === 'claude') {
      execSync('pbcopy', { input: prompt });
      execSync('open "https://claude.ai/new"');
      console.log(` ${pc.green('✓')} Prompt copied to clipboard.`);
      console.log(` ${pc.cyan('→')} Paste into claude.ai/new\n`);
    } else if (platform === 'gemini') {
      execSync('pbcopy', { input: prompt });
      execSync('open "https://gemini.google.com/app"');
      console.log(` ${pc.green('✓')} Prompt copied to clipboard.`);
      console.log(` ${pc.cyan('→')} Paste into Gemini\n`);
    } else if (platform === 'perplexity') {
      execSync('pbcopy', { input: prompt });
      execSync('open "https://perplexity.ai"');
      console.log(` ${pc.green('✓')} Prompt copied to clipboard.`);
      console.log(` ${pc.cyan('→')} Paste into Perplexity\n`);
    } else if (platform === 'hermes') {
      execSync('pbcopy', { input: prompt });
      console.log(` ${pc.green('✓')} Prompt copied to clipboard.`);
      console.log(`\n ${pc.cyan('→')} Continue this conversation in Hermes. Paste the prompt above.\n`);
      console.log(` ${pc.dim('Tip: say "draft a 3-day prompt skill routine" after pasting.')}\n`);
    }
  } catch (e) {
    console.log(`\n ${pc.red('✗')} Could not open browser. Copy the prompt below and open your AI manually:\n`);
    console.log(pc.dim(prompt));
  }
}
